############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/uqm/comm/arilou/arilou.cmake")
include("src/uqm/comm/blackur/blackur.cmake")
include("src/uqm/comm/chmmr/chmmr.cmake")
include("src/uqm/comm/comandr/comandr.cmake")
include("src/uqm/comm/druuge/druuge.cmake")
include("src/uqm/comm/ilwrath/ilwrath.cmake")
include("src/uqm/comm/melnorm/melnorm.cmake")
include("src/uqm/comm/mycon/mycon.cmake")
include("src/uqm/comm/orz/orz.cmake")
include("src/uqm/comm/pkunk/pkunk.cmake")
include("src/uqm/comm/rebel/rebel.cmake")
include("src/uqm/comm/shofixt/shofixt.cmake")
include("src/uqm/comm/slyhome/slyhome.cmake")
include("src/uqm/comm/slyland/slyland.cmake")
include("src/uqm/comm/spahome/spahome.cmake")
include("src/uqm/comm/spathi/spathi.cmake")
include("src/uqm/comm/starbas/starbas.cmake")
include("src/uqm/comm/supox/supox.cmake")
include("src/uqm/comm/syreen/syreen.cmake")
include("src/uqm/comm/talkpet/talkpet.cmake")
include("src/uqm/comm/thradd/thradd.cmake")
include("src/uqm/comm/umgah/umgah.cmake")
include("src/uqm/comm/urquan/urquan.cmake")
include("src/uqm/comm/utwig/utwig.cmake")
include("src/uqm/comm/vux/vux.cmake")
include("src/uqm/comm/yehat/yehat.cmake")
include("src/uqm/comm/zoqfot/zoqfot.cmake")


set(uqm_src_uqm_comm_files
	"src/uqm/comm/comm.cmake"
	"src/uqm/comm/commall.h"
)

source_group("src\\uqm\\comm" FILES ${uqm_src_uqm_comm_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_comm_files})
