############################################################


set(uqm_src_uqm_comm_master_files "")

############################################################
# Sub-directories
include("src/uqm/comm/arilou/arilou.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_arilou_master_files})
include("src/uqm/comm/blackur/blackur.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_blackur_master_files})
include("src/uqm/comm/chmmr/chmmr.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_chmmr_master_files})
include("src/uqm/comm/comandr/comandr.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_comandr_master_files})
include("src/uqm/comm/druuge/druuge.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_druuge_master_files})
include("src/uqm/comm/ilwrath/ilwrath.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_ilwrath_master_files})
include("src/uqm/comm/melnorm/melnorm.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_melnorm_master_files})
include("src/uqm/comm/mycon/mycon.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_mycon_master_files})
include("src/uqm/comm/orz/orz.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_orz_master_files})
include("src/uqm/comm/pkunk/pkunk.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_pkunk_master_files})
include("src/uqm/comm/rebel/rebel.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_rebel_master_files})
include("src/uqm/comm/shofixt/shofixt.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_shofixt_master_files})
include("src/uqm/comm/slyhome/slyhome.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_slyhome_master_files})
include("src/uqm/comm/slyland/slyland.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_slyland_master_files})
include("src/uqm/comm/spahome/spahome.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_spahome_master_files})
include("src/uqm/comm/spathi/spathi.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_spathi_master_files})
include("src/uqm/comm/starbas/starbas.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_starbas_master_files})
include("src/uqm/comm/supox/supox.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_supox_master_files})
include("src/uqm/comm/syreen/syreen.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_syreen_master_files})
include("src/uqm/comm/talkpet/talkpet.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_talkpet_master_files})
include("src/uqm/comm/thradd/thradd.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_thradd_master_files})
include("src/uqm/comm/umgah/umgah.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_umgah_master_files})
include("src/uqm/comm/urquan/urquan.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_urquan_master_files})
include("src/uqm/comm/utwig/utwig.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_utwig_master_files})
include("src/uqm/comm/vux/vux.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_vux_master_files})
include("src/uqm/comm/yehat/yehat.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_yehat_master_files})
include("src/uqm/comm/zoqfot/zoqfot.cmake")
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_zoqfot_master_files})

############################################################
# Local files
set(uqm_src_uqm_comm_files
	"src/uqm/comm/comm.cmake"
	"src/uqm/comm/commall.h"
)

source_group("src\\uqm\\comm" FILES ${uqm_src_uqm_comm_files})
list(APPEND uqm_src_uqm_comm_master_files ${uqm_src_uqm_comm_files})
