############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_ships_arilou_files
	"src/uqm/ships/arilou/arilou.cmake"
	"src/uqm/ships/arilou/arilou.cpp"
	"src/uqm/ships/arilou/arilou.h"
	"src/uqm/ships/arilou/icode.h"
	"src/uqm/ships/arilou/resinst.h"
)

source_group("src\\uqm\\ships\\arilou" FILES ${uqm_src_uqm_ships_arilou_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_ships_arilou_files})
