############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/libs/time/sdl/sdl.cmake")


set(uqm_src_libs_time_files
	"src/libs/time/time.cmake"
	"src/libs/time/timecommon.cpp"
	"src/libs/time/timecommon.h"
)

source_group("src\\libs\\time" FILES ${uqm_src_libs_time_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_time_files})
