############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/libs/sound/mixer/nosound/nosound.cmake")
include("src/libs/sound/mixer/sdl/sdl.cmake")


set(uqm_src_libs_sound_mixer_files
	"src/libs/sound/mixer/mixer.cmake"
	"src/libs/sound/mixer/mixer.cpp"
	"src/libs/sound/mixer/mixer.h"
	"src/libs/sound/mixer/mixerint.h"
)

source_group("src\\libs\\sound\\mixer" FILES ${uqm_src_libs_sound_mixer_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_sound_mixer_files})
