############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_uio_stdio_files
	"src/libs/uio/stdio/stdio.cmake"
	"src/libs/uio/stdio/stdio.cpp"
	"src/libs/uio/stdio/stdio.h"
)

source_group("src\\libs\\uio\\stdio" FILES ${uqm_src_libs_uio_stdio_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_uio_stdio_files})
