############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_math_files
	"src/libs/math/math.cmake"
	"src/libs/math/mthintrn.h"
	"src/libs/math/random.cpp"
	"src/libs/math/random.h"
	"src/libs/math/random2.cpp"
	"src/libs/math/sqrt.cpp"
)

source_group("src\\libs\\math" FILES ${uqm_src_libs_math_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_math_files})
