############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_comm_mycon_files
	"src/uqm/comm/mycon/mycon.cmake"
	"src/uqm/comm/mycon/myconc.cpp"
	"src/uqm/comm/mycon/resinst.h"
	"src/uqm/comm/mycon/strings.h"
)

source_group("src\\uqm\\comm\\mycon" FILES ${uqm_src_uqm_comm_mycon_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_comm_mycon_files})
