############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_decomp_files
	"src/libs/decomp/decomp.cmake"
	"src/libs/decomp/lzdecode.cpp"
	"src/libs/decomp/lzencode.cpp"
	"src/libs/decomp/lzh.h"
	"src/libs/decomp/update.cpp"
)

source_group("src\\libs\\decomp" FILES ${uqm_src_libs_decomp_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_decomp_files})
