############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_doc_fonts_files
    "doc/fonts/Fonts in use.txt"
    "doc/fonts/UQM-3DOMenuLabels.ttf"
    "doc/fonts/UQM-Arilou-Regular.ttf"
    "doc/fonts/UQM-ButtonFont.ttf"
    "doc/fonts/UQM-ChmmrFont.ttf"
    "doc/fonts/UQM-CommanderFont.ttf"
    "doc/fonts/UQM-Ilwrath-Regular.ttf"
    "doc/fonts/UQM-KohrAh-Regular.ttf"
    "doc/fonts/UQM-LanderFont.ttf"
    "doc/fonts/UQM-LoadMenuLabels.ttf"
    "doc/fonts/UQM-MeleeLabels.ttf"
    "doc/fonts/UQM-MicroFont.ttf"
    "doc/fonts/UQM-MicroThinFont.ttf"
    "doc/fonts/UQM-ModuleFont.ttf"
    "doc/fonts/UQM-PlayerFont.ttf"
    "doc/fonts/UQM-SUPER-MELEE.ttf"
    "doc/fonts/UQM-Slides.ttf"
    "doc/fonts/UQM-Spathi-Regular.ttf"
    "doc/fonts/UQM-Square-Regular.ttf"
    "doc/fonts/UQM-StarConFont.ttf"
    "doc/fonts/UQM-Supox-Regular.ttf"
    "doc/fonts/UQM-TinyFont.ttf"
    "doc/fonts/UQM-TinyFontBold.ttf"
    "doc/fonts/UQM-TinyFontCond.ttf"
    "doc/fonts/UQM-UrQuan-Regular.ttf"
    "doc/fonts/fonts.cmake"
)

source_group("doc\\fonts" FILES ${uqm_doc_fonts_files})
list(APPEND uqm_project_files_master ${uqm_doc_fonts_files})
