############################################################


set(uqm_src_uqm_master_files "")

############################################################
# Sub-directories
include("src/uqm/comm/comm.cmake")
list(APPEND uqm_src_uqm_master_files ${uqm_src_uqm_comm_master_files})
include("src/uqm/lua/lua.cmake")
list(APPEND uqm_src_uqm_master_files ${uqm_src_uqm_lua_master_files})
include("src/uqm/planets/planets.cmake")
list(APPEND uqm_src_uqm_master_files ${uqm_src_uqm_planets_master_files})
include("src/uqm/ships/ships.cmake")
list(APPEND uqm_src_uqm_master_files ${uqm_src_uqm_ships_master_files})
include("src/uqm/supermelee/supermelee.cmake")
list(APPEND uqm_src_uqm_master_files ${uqm_src_uqm_supermelee_master_files})

############################################################
# Local files
set(uqm_src_uqm_files
	"src/uqm/StarmapGlobalData.h"
	"src/uqm/battle.cpp"
	"src/uqm/battle.h"
	"src/uqm/battlecontrols.cpp"
	"src/uqm/battlecontrols.h"
	"src/uqm/border.cpp"
	"src/uqm/build.cpp"
	"src/uqm/build.h"
	"src/uqm/cleanup.cpp"
	"src/uqm/clock.cpp"
	"src/uqm/clock.h"
	"src/uqm/cnctdlg.cpp"
	"src/uqm/cnctdlg.h"
	"src/uqm/coderes.h"
	"src/uqm/collide.cpp"
	"src/uqm/collide.h"
	"src/uqm/colors.h"
	"src/uqm/comm.cpp"
	"src/uqm/comm.h"
	"src/uqm/commanim.cpp"
	"src/uqm/commanim.h"
	"src/uqm/commglue.cpp"
	"src/uqm/commglue.h"
	"src/uqm/confirm.cpp"
	"src/uqm/cons_res.cpp"
	"src/uqm/cons_res.h"
	"src/uqm/controls.h"
	"src/uqm/corecode.h"
	"src/uqm/credits.cpp"
	"src/uqm/credits.h"
	"src/uqm/cyborg.cpp"
#	"src/uqm/demo.cpp"
	"src/uqm/demo.h"
	"src/uqm/displist.cpp"
	"src/uqm/displist.h"
	"src/uqm/dummy.cpp"
	"src/uqm/dummy.h"
	"src/uqm/element.h"
	"src/uqm/encount.cpp"
	"src/uqm/encount.h"
	"src/uqm/flash.cpp"
	"src/uqm/flash.h"
	"src/uqm/fmv.cpp"
	"src/uqm/fmv.h"
	"src/uqm/galaxy.cpp"
	"src/uqm/gameev.cpp"
	"src/uqm/gameev.h"
	"src/uqm/gameinp.cpp"
	"src/uqm/gameopt.cpp"
	"src/uqm/gameopt.h"
	"src/uqm/gamestr.h"
	"src/uqm/gendef.cpp"
	"src/uqm/gendef.h"
	"src/uqm/getchar.cpp"
	"src/uqm/globdata.cpp"
	"src/uqm/globdata.h"
	"src/uqm/gravity.cpp"
	"src/uqm/grpinfo.cpp"
	"src/uqm/grpinfo.h"
	"src/uqm/grpintrn.h"
	"src/uqm/hyper.cpp"
	"src/uqm/hyper.h"
	"src/uqm/ifontres.h"
	"src/uqm/igfxres.h"
	"src/uqm/ikey_con.h"
	"src/uqm/imusicre.h"
	"src/uqm/init.cpp"
	"src/uqm/init.h"
	"src/uqm/intel.cpp"
	"src/uqm/intel.h"
	"src/uqm/intro.cpp"
	"src/uqm/ipdisp.cpp"
	"src/uqm/ipdisp.h"
#	"src/uqm/iscriptres.h"
	"src/uqm/isndres.h"
	"src/uqm/istrtab.h"
	"src/uqm/load.cpp"
	"src/uqm/load_legacy.cpp"
	"src/uqm/loadship.cpp"
	"src/uqm/master.cpp"
	"src/uqm/master.h"
	"src/uqm/menu.cpp"
	"src/uqm/menustat.h"
	"src/uqm/misc.cpp"
	"src/uqm/nameref.h"
	"src/uqm/oscill.cpp"
	"src/uqm/oscill.h"
	"src/uqm/outfit.cpp"
	"src/uqm/pickship.cpp"
	"src/uqm/pickship.h"
	"src/uqm/process.cpp"
	"src/uqm/process.h"
	"src/uqm/races.h"
	"src/uqm/resinst.h"
	"src/uqm/restart.cpp"
	"src/uqm/restart.h"
	"src/uqm/save.cpp"
	"src/uqm/save.h"
	"src/uqm/settings.cpp"
	"src/uqm/settings.h"
	"src/uqm/setup.cpp"
	"src/uqm/setup.h"
	"src/uqm/setupmenu.cpp"
	"src/uqm/setupmenu.h"
	"src/uqm/ship.cpp"
	"src/uqm/ship.h"
	"src/uqm/shipcont.h"
	"src/uqm/shipstat.cpp"
	"src/uqm/shipyard.cpp"
	"src/uqm/sis.cpp"
	"src/uqm/sis.h"
	"src/uqm/sounds.cpp"
	"src/uqm/sounds.h"
	"src/uqm/starbase.cpp"
	"src/uqm/starbase.h"
	"src/uqm/starcon.cpp"
	"src/uqm/starcon.h"
	"src/uqm/starmap.cpp"
	"src/uqm/starmap.h"
	"src/uqm/state.cpp"
	"src/uqm/state.h"
	"src/uqm/status.cpp"
	"src/uqm/status.h"
	"src/uqm/tactrans.cpp"
	"src/uqm/tactrans.h"
	"src/uqm/trans.cpp"
	"src/uqm/units.h"
	"src/uqm/uqm.cmake"
	"src/uqm/uqmdebug.cpp"
	"src/uqm/uqmdebug.h"
	"src/uqm/util.cpp"
	"src/uqm/util.h"
	"src/uqm/velocity.cpp"
	"src/uqm/velocity.h"
	"src/uqm/weapon.cpp"
	"src/uqm/weapon.h"
)

source_group("src\\uqm" FILES ${uqm_src_uqm_files})
list(APPEND uqm_src_uqm_master_files ${uqm_src_uqm_files})
