############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_threads_sdl_files
	"src/libs/threads/sdl/sdl.cmake"
	"src/libs/threads/sdl/sdlthreads.cpp"
	"src/libs/threads/sdl/sdlthreads.h"
)

source_group("src\\libs\\threads\\sdl" FILES ${uqm_src_libs_threads_sdl_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_threads_sdl_files})
