############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_task_files
	"src/libs/task/task.cmake"
	"src/libs/task/tasklib.cpp"
)

source_group("src\\libs\\task" FILES ${uqm_src_libs_task_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_task_files})
