############################################################


set(uqm_src_libs_lua_master_files "")


############################################################
# Local files
set(uqm_src_libs_lua_files
	"src/libs/lua/lapi.cpp"
	"src/libs/lua/lapi.h"
	"src/libs/lua/lauxlib.cpp"
	"src/libs/lua/lauxlib.h"
	"src/libs/lua/lbaselib.cpp"
	"src/libs/lua/lbitlib.cpp"
	"src/libs/lua/lcode.cpp"
	"src/libs/lua/lcode.h"
#	"src/libs/lua/lcorolib.cpp"
	"src/libs/lua/lctype.cpp"
	"src/libs/lua/lctype.h"
#	"src/libs/lua/ldblib.cpp"
	"src/libs/lua/ldebug.cpp"
	"src/libs/lua/ldebug.h"
	"src/libs/lua/ldo.cpp"
	"src/libs/lua/ldo.h"
	"src/libs/lua/ldump.cpp"
	"src/libs/lua/lfunc.cpp"
	"src/libs/lua/lfunc.h"
	"src/libs/lua/lgc.cpp"
	"src/libs/lua/lgc.h"
#	"src/libs/lua/linit.cpp"
#	"src/libs/lua/liolib.cpp"
	"src/libs/lua/llex.cpp"
	"src/libs/lua/llex.h"
	"src/libs/lua/llimits.h"
	"src/libs/lua/lmathlib.cpp"
	"src/libs/lua/lmem.cpp"
	"src/libs/lua/lmem.h"
#	"src/libs/lua/loadlib.cpp"
	"src/libs/lua/lobject.cpp"
	"src/libs/lua/lobject.h"
	"src/libs/lua/lopcodes.cpp"
	"src/libs/lua/lopcodes.h"
#	"src/libs/lua/loslib.cpp"
	"src/libs/lua/lparser.cpp"
	"src/libs/lua/lparser.h"
	"src/libs/lua/lstate.cpp"
	"src/libs/lua/lstate.h"
	"src/libs/lua/lstring.cpp"
	"src/libs/lua/lstring.h"
	"src/libs/lua/lstrlib.cpp"
	"src/libs/lua/ltable.cpp"
	"src/libs/lua/ltable.h"
	"src/libs/lua/ltablib.cpp"
	"src/libs/lua/ltm.cpp"
	"src/libs/lua/ltm.h"
	"src/libs/lua/lua.cmake"
#	"src/libs/lua/lua.cpp"
	"src/libs/lua/lua.h"
#	"src/libs/lua/lua.hpp"
#	"src/libs/lua/luac.cpp"
	"src/libs/lua/luaconf.h"
	"src/libs/lua/lualib.h"
	"src/libs/lua/lundump.cpp"
	"src/libs/lua/lundump.h"
	"src/libs/lua/lvm.cpp"
	"src/libs/lua/lvm.h"
	"src/libs/lua/lzio.cpp"
	"src/libs/lua/lzio.h"
)

source_group("src\\libs\\lua" FILES ${uqm_src_libs_lua_files})
list(APPEND uqm_src_libs_lua_master_files ${uqm_src_libs_lua_files})
