############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_sound_mixer_nosound_files
	"src/libs/sound/mixer/nosound/audiodrv_nosound.cpp"
	"src/libs/sound/mixer/nosound/audiodrv_nosound.h"
	"src/libs/sound/mixer/nosound/nosound.cmake"
)

source_group("src\\libs\\sound\\mixer\\nosound" FILES ${uqm_src_libs_sound_mixer_nosound_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_sound_mixer_nosound_files})
