############################################################


set(uqm_src_uqm_ships_master_files "")

############################################################
# Sub-directories
include("src/uqm/ships/androsyn/androsyn.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_androsyn_master_files})
include("src/uqm/ships/arilou/arilou.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_arilou_master_files})
include("src/uqm/ships/blackurq/blackurq.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_blackurq_master_files})
include("src/uqm/ships/chenjesu/chenjesu.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_chenjesu_master_files})
include("src/uqm/ships/chmmr/chmmr.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_chmmr_master_files})
include("src/uqm/ships/druuge/druuge.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_druuge_master_files})
include("src/uqm/ships/human/human.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_human_master_files})
include("src/uqm/ships/ilwrath/ilwrath.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_ilwrath_master_files})
include("src/uqm/ships/lastbat/lastbat.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_lastbat_master_files})
include("src/uqm/ships/melnorme/melnorme.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_melnorme_master_files})
include("src/uqm/ships/mmrnmhrm/mmrnmhrm.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_mmrnmhrm_master_files})
include("src/uqm/ships/mycon/mycon.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_mycon_master_files})
include("src/uqm/ships/orz/orz.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_orz_master_files})
include("src/uqm/ships/pkunk/pkunk.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_pkunk_master_files})
include("src/uqm/ships/probe/probe.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_probe_master_files})
include("src/uqm/ships/shofixti/shofixti.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_shofixti_master_files})
include("src/uqm/ships/sis_ship/sis_ship.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_sis_ship_master_files})
include("src/uqm/ships/slylandr/slylandr.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_slylandr_master_files})
include("src/uqm/ships/spathi/spathi.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_spathi_master_files})
include("src/uqm/ships/supox/supox.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_supox_master_files})
include("src/uqm/ships/syreen/syreen.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_syreen_master_files})
include("src/uqm/ships/thradd/thradd.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_thradd_master_files})
include("src/uqm/ships/umgah/umgah.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_umgah_master_files})
include("src/uqm/ships/urquan/urquan.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_urquan_master_files})
include("src/uqm/ships/utwig/utwig.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_utwig_master_files})
include("src/uqm/ships/vux/vux.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_vux_master_files})
include("src/uqm/ships/yehat/yehat.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_yehat_master_files})
include("src/uqm/ships/zoqfot/zoqfot.cmake")
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_zoqfot_master_files})

############################################################
# Local files
set(uqm_src_uqm_ships_files
	"src/uqm/ships/ship.h"
	"src/uqm/ships/ships.cmake"
)

source_group("src\\uqm\\ships" FILES ${uqm_src_uqm_ships_files})
list(APPEND uqm_src_uqm_ships_master_files ${uqm_src_uqm_ships_files})
