############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/uqm/ships/androsyn/androsyn.cmake")
include("src/uqm/ships/arilou/arilou.cmake")
include("src/uqm/ships/blackurq/blackurq.cmake")
include("src/uqm/ships/chenjesu/chenjesu.cmake")
include("src/uqm/ships/chmmr/chmmr.cmake")
include("src/uqm/ships/druuge/druuge.cmake")
include("src/uqm/ships/human/human.cmake")
include("src/uqm/ships/ilwrath/ilwrath.cmake")
include("src/uqm/ships/lastbat/lastbat.cmake")
include("src/uqm/ships/melnorme/melnorme.cmake")
include("src/uqm/ships/mmrnmhrm/mmrnmhrm.cmake")
include("src/uqm/ships/mycon/mycon.cmake")
include("src/uqm/ships/orz/orz.cmake")
include("src/uqm/ships/pkunk/pkunk.cmake")
include("src/uqm/ships/probe/probe.cmake")
include("src/uqm/ships/shofixti/shofixti.cmake")
include("src/uqm/ships/sis_ship/sis_ship.cmake")
include("src/uqm/ships/slylandr/slylandr.cmake")
include("src/uqm/ships/spathi/spathi.cmake")
include("src/uqm/ships/supox/supox.cmake")
include("src/uqm/ships/syreen/syreen.cmake")
include("src/uqm/ships/thradd/thradd.cmake")
include("src/uqm/ships/umgah/umgah.cmake")
include("src/uqm/ships/urquan/urquan.cmake")
include("src/uqm/ships/utwig/utwig.cmake")
include("src/uqm/ships/vux/vux.cmake")
include("src/uqm/ships/yehat/yehat.cmake")
include("src/uqm/ships/zoqfot/zoqfot.cmake")


set(uqm_src_uqm_ships_files
	"src/uqm/ships/ship.h"
	"src/uqm/ships/ships.cmake"
)

source_group("src\\uqm\\ships" FILES ${uqm_src_uqm_ships_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_ships_files})
