############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_ships_pkunk_files
	"src/uqm/ships/pkunk/icode.h"
	"src/uqm/ships/pkunk/pkunk.cmake"
	"src/uqm/ships/pkunk/pkunk.cpp"
	"src/uqm/ships/pkunk/pkunk.h"
	"src/uqm/ships/pkunk/resinst.h"
)

source_group("src\\uqm\\ships\\pkunk" FILES ${uqm_src_uqm_ships_pkunk_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_ships_pkunk_files})
