############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_comm_blackur_files
	"src/uqm/comm/blackur/blackur.cmake"
	"src/uqm/comm/blackur/blackurc.cpp"
	"src/uqm/comm/blackur/resinst.h"
	"src/uqm/comm/blackur/strings.h"
)

source_group("src\\uqm\\comm\\blackur" FILES ${uqm_src_uqm_comm_blackur_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_comm_blackur_files})
