############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_comm_ilwrath_files
	"src/uqm/comm/ilwrath/ilwrath.cmake"
	"src/uqm/comm/ilwrath/ilwrathc.cpp"
	"src/uqm/comm/ilwrath/resinst.h"
	"src/uqm/comm/ilwrath/strings.h"
)

source_group("src\\uqm\\comm\\ilwrath" FILES ${uqm_src_uqm_comm_ilwrath_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_comm_ilwrath_files})
