############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_ships_shofixti_files
	"src/uqm/ships/shofixti/icode.h"
	"src/uqm/ships/shofixti/resinst.h"
	"src/uqm/ships/shofixti/shofixti.cmake"
	"src/uqm/ships/shofixti/shofixti.cpp"
	"src/uqm/ships/shofixti/shofixti.h"
)

source_group("src\\uqm\\ships\\shofixti" FILES ${uqm_src_uqm_ships_shofixti_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_ships_shofixti_files})
