############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_doc_users_files
    "doc/users/manual.txt"
    "doc/users/unixinstall"
    "doc/users/uqm.6"
    "doc/users/users.cmake"
)

source_group("doc\\users" FILES ${uqm_doc_users_files})
list(APPEND uqm_project_files_master ${uqm_doc_users_files})
