############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_list_files
	"src/libs/list/list.cmake"
	"src/libs/list/list.cpp"
	"src/libs/list/list.h"
)

source_group("src\\libs\\list" FILES ${uqm_src_libs_list_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_list_files})
