############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_heap_files
	"src/libs/heap/heap.cmake"
	"src/libs/heap/heap.cpp"
	"src/libs/heap/heap.h"
)

source_group("src\\libs\\heap" FILES ${uqm_src_libs_heap_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_heap_files})
