############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("doc/devel/devel.cmake")
include("doc/fonts/fonts.cmake")
include("doc/release/release.cmake")
include("doc/users/users.cmake")


set(uqm_doc_files
    "doc/doc.cmake"
)

source_group("doc" FILES ${uqm_doc_files})
list(APPEND uqm_project_files_master ${uqm_doc_files})
