############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_lua_luafuncs_files
#	"src/uqm/lua/luafuncs/README.txt"
	"src/uqm/lua/luafuncs/commfuncs.cpp"
	"src/uqm/lua/luafuncs/commfuncs.h"
	"src/uqm/lua/luafuncs/customfuncs.cpp"
	"src/uqm/lua/luafuncs/customfuncs.h"
	"src/uqm/lua/luafuncs/eventfuncs.cpp"
	"src/uqm/lua/luafuncs/eventfuncs.h"
	"src/uqm/lua/luafuncs/logfuncs.cpp"
	"src/uqm/lua/luafuncs/logfuncs.h"
	"src/uqm/lua/luafuncs/luafuncs.cmake"
	"src/uqm/lua/luafuncs/statefuncs.cpp"
	"src/uqm/lua/luafuncs/statefuncs.h"
)

source_group("src\\uqm\\lua\\luafuncs" FILES ${uqm_src_uqm_lua_luafuncs_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_lua_luafuncs_files})
