############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_ships_orz_files
	"src/uqm/ships/orz/icode.h"
	"src/uqm/ships/orz/orz.cmake"
	"src/uqm/ships/orz/orz.cpp"
	"src/uqm/ships/orz/orz.h"
	"src/uqm/ships/orz/resinst.h"
)

source_group("src\\uqm\\ships\\orz" FILES ${uqm_src_uqm_ships_orz_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_ships_orz_files})
