############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_file_files
	"src/libs/file/dirs.cpp"
	"src/libs/file/file.cmake"
	"src/libs/file/files.cpp"
	"src/libs/file/filintrn.h"
#	"src/libs/file/temp.cpp"
)

source_group("src\\libs\\file" FILES ${uqm_src_libs_file_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_file_files})
