############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_video_files
	"src/libs/video/dukvid.cpp"
	"src/libs/video/dukvid.h"
	"src/libs/video/legacyplayer.cpp"
	"src/libs/video/vfileins.cpp"
	"src/libs/video/video.cmake"
	"src/libs/video/video.cpp"
	"src/libs/video/video.h"
	"src/libs/video/videodec.cpp"
	"src/libs/video/videodec.h"
	"src/libs/video/vidintrn.h"
	"src/libs/video/vidplayer.cpp"
	"src/libs/video/vidplayer.h"
	"src/libs/video/vresins.cpp"
)

source_group("src\\libs\\video" FILES ${uqm_src_libs_video_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_video_files})
