############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/libs/callback/callback.cmake")
# include("src/libs/cdp/cdp.cmake")
include("src/libs/decomp/decomp.cmake")
include("src/libs/file/file.cmake")
include("src/libs/graphics/graphics.cmake")
include("src/libs/heap/heap.cmake")
include("src/libs/input/input.cmake")
include("src/libs/list/list.cmake")
include("src/libs/log/log.cmake")
include("src/libs/lua/lua.cmake")
include("src/libs/luauqm/luauqm.cmake")
include("src/libs/math/math.cmake")
include("src/libs/md5/md5.cmake")
include("src/libs/memory/memory.cmake")
include("src/libs/mikmod/mikmod.cmake")
include("src/libs/network/network.cmake")
include("src/libs/resource/resource.cmake")
include("src/libs/sound/sound.cmake")
include("src/libs/strings/strings.cmake")
include("src/libs/task/task.cmake")
include("src/libs/threads/threads.cmake")
include("src/libs/time/time.cmake")
include("src/libs/uio/uio.cmake")
include("src/libs/video/video.cmake")


set(uqm_src_libs_files
	"src/libs/async.h"
#	"src/libs/cdplib.h"
	"src/libs/compiler.h"
	"src/libs/declib.h"
	"src/libs/file.h"
	"src/libs/gfxlib.h"
	"src/libs/heap.h"
	"src/libs/inplib.h"
	"src/libs/libs.cmake"
	"src/libs/list.h"
	"src/libs/log.h"
	"src/libs/mathlib.h"
	"src/libs/md5.h"
	"src/libs/memlib.h"
	"src/libs/misc.h"
	"src/libs/net.h"
	"src/libs/platform.h"
	"src/libs/reslib.h"
#	"src/libs/scriptlib.h"
	"src/libs/sndlib.h"
	"src/libs/strlib.h"
	"src/libs/tasklib.h"
	"src/libs/threadlib.h"
	"src/libs/timelib.h"
	"src/libs/uio.h"
#	"src/libs/uioutils.h"
	"src/libs/unicode.h"
	"src/libs/vidlib.h"
)

source_group("src\\libs" FILES ${uqm_src_libs_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_files})
