############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/libs/input/sdl/sdl.cmake")


set(uqm_src_libs_input_files
	"src/libs/input/inpintrn.h"
	"src/libs/input/input.cmake"
	"src/libs/input/input_common.cpp"
	"src/libs/input/input_common.h"
)

source_group("src\\libs\\input" FILES ${uqm_src_libs_input_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_input_files})
