############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_time_sdl_files
	"src/libs/time/sdl/sdl.cmake"
	"src/libs/time/sdl/sdltime.cpp"
	"src/libs/time/sdl/sdltime.h"
)

source_group("src\\libs\\time\\sdl" FILES ${uqm_src_libs_time_sdl_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_time_sdl_files})
