############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_ships_blackurq_files
	"src/uqm/ships/blackurq/blackurq.cmake"
	"src/uqm/ships/blackurq/blackurq.cpp"
	"src/uqm/ships/blackurq/blackurq.h"
	"src/uqm/ships/blackurq/icode.h"
	"src/uqm/ships/blackurq/resinst.h"
)

source_group("src\\uqm\\ships\\blackurq" FILES ${uqm_src_uqm_ships_blackurq_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_ships_blackurq_files})
