############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


# include("src/libs/threads/pthread/pthread.cmake")
include("src/libs/threads/sdl/sdl.cmake")


set(uqm_src_libs_threads_files
	"src/libs/threads/thrcommon.cpp"
	"src/libs/threads/thrcommon.h"
	"src/libs/threads/threads.cmake"
)

source_group("src\\libs\\threads" FILES ${uqm_src_libs_threads_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_threads_files})
