############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/libs/sound/decoders/decoders.cmake")
include("src/libs/sound/mixer/mixer.cmake")
include("src/libs/sound/openal/openal.cmake")


set(uqm_src_libs_sound_files
	"src/libs/sound/audiocore.cpp"
	"src/libs/sound/audiocore.h"
	"src/libs/sound/fileinst.cpp"
	"src/libs/sound/music.cpp"
	"src/libs/sound/resinst.cpp"
	"src/libs/sound/sfx.cpp"
	"src/libs/sound/sndintrn.h"
	"src/libs/sound/sound.cmake"
	"src/libs/sound/sound.cpp"
	"src/libs/sound/sound.h"
	"src/libs/sound/stream.cpp"
	"src/libs/sound/stream.h"
	"src/libs/sound/trackint.h"
	"src/libs/sound/trackplayer.cpp"
	"src/libs/sound/trackplayer.h"
)

source_group("src\\libs\\sound" FILES ${uqm_src_libs_sound_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_sound_files})
