############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_memory_files
	"src/libs/memory/memory.cmake"
	"src/libs/memory/w_memlib.cpp"
)

source_group("src\\libs\\memory" FILES ${uqm_src_libs_memory_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_memory_files})
