############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_network_socket_files
	"src/libs/network/socket/socket.cmake"
	"src/libs/network/socket/socket.cpp"
	"src/libs/network/socket/socket.h"
#	"src/libs/network/socket/socket_bsd.cpp"
#	"src/libs/network/socket/socket_bsd.h"
	"src/libs/network/socket/socket_win.cpp"
	"src/libs/network/socket/socket_win.h"
)

source_group("src\\libs\\network\\socket" FILES ${uqm_src_libs_network_socket_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_network_socket_files})
