############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_getopt_files
	"src/getopt/getopt.cmake"
	"src/getopt/getopt.cpp"
	"src/getopt/getopt.h"
	"src/getopt/getopt1.cpp"
)

source_group("src\\getopt" FILES ${uqm_src_getopt_files})
list(APPEND uqm_project_files_master ${uqm_src_getopt_files})
