############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/core/memory/memory.cmake")


set(uqm_src_core_files
	"src/core/core.cmake"
)

source_group("src\\core" FILES ${uqm_src_core_files})
list(APPEND uqm_project_files_master ${uqm_src_core_files})
