############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_strings_files
	"src/libs/strings/getstr.cpp"
	"src/libs/strings/sfileins.cpp"
	"src/libs/strings/sresins.cpp"
	"src/libs/strings/stringhashtable.cpp"
	"src/libs/strings/stringhashtable.h"
	"src/libs/strings/strings.cmake"
	"src/libs/strings/strings.cpp"
	"src/libs/strings/strintrn.h"
	"src/libs/strings/unicode.cpp"
)

source_group("src\\libs\\strings" FILES ${uqm_src_libs_strings_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_strings_files})
