############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_comm_spahome_files
	"src/uqm/comm/spahome/spahome.cmake"
	"src/uqm/comm/spahome/spahome.cpp"
	"src/uqm/comm/spahome/strings.h"
)

source_group("src\\uqm\\comm\\spahome" FILES ${uqm_src_uqm_comm_spahome_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_comm_spahome_files})
