############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


include("src/libs/network/connect/connect.cmake")
include("src/libs/network/netmanager/netmanager.cmake")
include("src/libs/network/socket/socket.cmake")


set(uqm_src_libs_network_files
#	"src/libs/network/FILES"
	"src/libs/network/bytesex.h"
	"src/libs/network/netport.cpp"
	"src/libs/network/netport.h"
	"src/libs/network/network.cmake"
	"src/libs/network/network.h"
#	"src/libs/network/network_bsd.cpp"
	"src/libs/network/network_win.cpp"
	"src/libs/network/wspiapiwrap.cpp"
	"src/libs/network/wspiapiwrap.h"
)

source_group("src\\libs\\network" FILES ${uqm_src_libs_network_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_network_files})
