############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_sound_mixer_sdl_files
	"src/libs/sound/mixer/sdl/audiodrv_sdl.cpp"
	"src/libs/sound/mixer/sdl/audiodrv_sdl.h"
	"src/libs/sound/mixer/sdl/sdl.cmake"
)

source_group("src\\libs\\sound\\mixer\\sdl" FILES ${uqm_src_libs_sound_mixer_sdl_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_sound_mixer_sdl_files})
