############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_libs_uio_zip_files
	"src/libs/uio/zip/zip.cmake"
	"src/libs/uio/zip/zip.cpp"
	"src/libs/uio/zip/zip.h"
)

source_group("src\\libs\\uio\\zip" FILES ${uqm_src_libs_uio_zip_files})
list(APPEND uqm_project_files_master ${uqm_src_libs_uio_zip_files})
