############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################


# include("src/core/core.cmake")
include("src/getopt/getopt.cmake")
include("src/libs/libs.cmake")
include("src/res/res.cmake")
include("src/uqm/uqm.cmake")


set(uqm_src_files
#	"src/.clang-format"
	"src/config.h"
#	"src/config_unix.h.in"
	"src/config_vc6.h"
#	"src/config_win.h"
#	"src/config_win.h.in"
	"src/endian_uqm.h"
	"src/options.cpp"
	"src/options.h"
	"src/port.cpp"
	"src/port.h"
	"src/src.cmake"
	"src/types.h"
	"src/uqm.cpp"
	"src/uqmversion.h"
)

source_group("src" FILES ${uqm_src_files})
list(APPEND uqm_project_files_master ${uqm_src_files})
