############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_uqm_ships_melnorme_files
	"src/uqm/ships/melnorme/icode.h"
	"src/uqm/ships/melnorme/melnorme.cmake"
	"src/uqm/ships/melnorme/melnorme.cpp"
	"src/uqm/ships/melnorme/melnorme.h"
	"src/uqm/ships/melnorme/resinst.h"
)

source_group("src\\uqm\\ships\\melnorme" FILES ${uqm_src_uqm_ships_melnorme_files})
list(APPEND uqm_project_files_master ${uqm_src_uqm_ships_melnorme_files})
