import os
from pathlib import Path
import sys
import re

IGNORED_FILES = ['Makeinfo']
VAR_PREFIX = 'uqm'
MASTER_UQM_FILES_LIST = 'uqm_project_files_master'
PATH_WHITELIST = []
FILE_WHITELIST = []

def load_whitelists(whitlelist_path):
	global PATH_WHITELIST, FILE_WHITELIST
	with open(whitlelist_path,'r') as win_files:
		for file_line in win_files:
			file_path = Path(file_line.strip())
			FILE_WHITELIST.append(file_path)
			if file_path.parent not in PATH_WHITELIST:
				PATH_WHITELIST.append(file_path.parent)

		

def generate_cmakefile(root, subdirs, files):
	file_text = '############################################################\n'
	file_text +='# Auto-generated by CMake/generate_directory_cmake_files.py.\n'
	file_text +='############################################################\n\n\n'
	
	sorted_subdirs = sorted(subdirs, key=lambda d: d.name)
	for subdir in sorted_subdirs:
		subdir_cmake = subdir / f'{subdir.name}.cmake'
		if subdir not in PATH_WHITELIST:
			file_text += "# "
		file_text += f'include("{str(subdir_cmake).replace('\\','/')}")\n'
			

	if files:
		file_vars_name = f'{VAR_PREFIX}_{'_'.join(root.parts)}_files'
		file_vars_as_cmake_value = '${' + file_vars_name + '}'
		file_text += f'\n\nset({file_vars_name}\n'

		sorted_files = sorted(files, key=lambda f: f.name)
		for file in sorted_files:
			if file.suffix != '.cmake' and file not in FILE_WHITELIST:
				file_text += "#"
			file_text += f'\t"{str(file).replace('\\','/')}"\n'

		file_text += ')\n\n'
		file_text += f'source_group("{str(root).replace('\\','\\\\')}" FILES {file_vars_as_cmake_value})\n'
		file_text += f'list(APPEND {MASTER_UQM_FILES_LIST} {file_vars_as_cmake_value})\n'

	cmake_file_path = root / f'{root.name}.cmake'
	with open(cmake_file_path, 'w') as cmake_file:
		cmake_file.write(file_text)



def walk_directory(path:Path):
	dirs = []
	files = []
	for dir_item in path.iterdir():
		if dir_item.is_dir():
			dirs.append(dir_item)
		else:
			if dir_item.name not in IGNORED_FILES:
				files.append(dir_item)

	generate_cmakefile(path, dirs, files)
	
	for dir in dirs:
		walk_directory(dir)

if __name__ == '__main__':
	if len(sys.argv) == 1:
		sys.argv.extend(['src', 'CMake/win_files.txt'])
	start_path = Path(sys.argv[1])
	whitlelist_path = Path(sys.argv[2])

	load_whitelists(whitlelist_path)
	walk_directory(start_path)
