import argparse
import os
from pathlib import Path
import sys
import re

IGNORED_FILES = ['Makeinfo']
VAR_PREFIX = 'uqm'
MASTER_UQM_FILES_LIST = 'uqm_project_files_master'
EXTENSION_WHITELIST = ['.cmake', '.clang-tidy', '.clang-format']
PATH_WHITELIST = []
FILE_WHITELIST = []

def load_whitelists(whitlelist_path):
	global PATH_WHITELIST, FILE_WHITELIST
	with open(whitlelist_path,'r') as win_files:
		for file_line in win_files:
			file_path = Path(file_line.strip())
			FILE_WHITELIST.append(file_path)
			if file_path.parent not in PATH_WHITELIST:
				PATH_WHITELIST.append(file_path.parent)

		
def get_directory_cmake_path(path):
	return path / f'{path.name}.cmake'

def get_directory_file_list_var(path, master):
	return f'{VAR_PREFIX}_{'_'.join(path.parts)}_{'master_' if master else ''}files'

def path_whitelisted(path):
	if PATH_WHITELIST:
		return path in PATH_WHITELIST
	return True

def file_whitelisted(file_path):
	if file_path.suffix in EXTENSION_WHITELIST:
		return True
	
	if FILE_WHITELIST:
		return file_path in FILE_WHITELIST
	return True

def generate_cmakefile(root, subdirs, files):
	file_text = '############################################################\n'
	file_text = '############################################################\n'
	file_text +='# Auto-generated by CMake/generate_directory_cmake_files.py.\n'
	file_text +='############################################################\n'
	file_text = '############################################################\n\n\n'
	

	file_master_vars_name = get_directory_file_list_var(root, True)
	file_text += f'set({file_master_vars_name} "")\n\n'

	if subdirs:
		file_text += '############################################################\n'
		file_text += "# Sub-directories\n"
		sorted_subdirs = sorted(subdirs, key=lambda d: d.name)
		for subdir in sorted_subdirs:
			subdir_cmake = get_directory_cmake_path(subdir)
			whitelisted = path_whitelisted(subdir)
			if not whitelisted:
				file_text += "# "
			file_text += f'include("{str(subdir_cmake).replace('\\','/')}")\n'
			if not whitelisted:
				file_text += "# "
			file_text += f'list(APPEND {file_master_vars_name} ${{{get_directory_file_list_var(subdir, True)}}})\n'
			

	if files:
		file_text += '\n############################################################\n'
		file_text += "# Local files\n"
		file_vars_name = get_directory_file_list_var(root, False)
		file_text += f'set({file_vars_name}\n'

		sorted_files = sorted(files, key=lambda f: f.name)
		for file in sorted_files:
			if not file_whitelisted(file):
					file_text += "#"
			file_text += f'\t"{str(file).replace('\\','/')}"\n'

		file_text += ')\n\n'
		file_text += f'source_group("{str(root).replace('\\','\\\\')}" FILES ${{{file_vars_name}}})\n'
		file_text += f'list(APPEND {file_master_vars_name} ${{{file_vars_name}}})\n'

	cmake_file_path = root / f'{root.name}.cmake'
	with open(cmake_file_path, 'w') as cmake_file:
		cmake_file.write(file_text)



def walk_directory(path:Path):
	dirs = []
	files = []
	for dir_item in path.iterdir():
		if dir_item.is_dir():
			dirs.append(dir_item)
		else:
			if dir_item.name not in IGNORED_FILES:
				files.append(dir_item)

	generate_cmakefile(path, dirs, files)
	
	for dir in dirs:
		walk_directory(dir)

if __name__ == '__main__':
	
	# no args given? Assume testing.
	if len(sys.argv) == 1:
		sys.argv.extend(['src', '-wl', 'CMake/win_files.txt'])
	
	parser = argparse.ArgumentParser()
	parser.add_argument('path', type=str, help='Path to build cmake files for')
	parser.add_argument('-w','--whitelist', type=str, help='Path to a whitelist control file', default='')
	parser.add_argument('-r','--root',  type=str, help='Root path to start from. Used for variable naming and "include" directives.', default='')
	parser.add_argument('-p', '--prefix',  type=str, help='Prefix to use when naming variables. default=%(default)s.', default='uqm')

	args = parser.parse_intermixed_args()
	
	VAR_PREFIX = args.prefix

	if args.whitelist:
		load_whitelists(Path(args.whitelist))
	
	cwd = os.getcwd()
	
	file_path = Path(args.path)
	if args.root:
		os.chdir(args.root)
		file_path = file_path.relative_to(args.root)
	walk_directory(file_path)
	
	os.chdir(cwd)

