############################################################
# Auto-generated by CMake/generate_directory_cmake_files.py.
############################################################




set(uqm_src_core_memory_files
	"src/core/memory/memory.cmake"
	"src/core/memory/memory.h"
)

source_group("src\\core\\memory" FILES ${uqm_src_core_memory_files})
list(APPEND uqm_project_files_master ${uqm_src_core_memory_files})
